spring.application.name=Daily-activity
spring.datasource.url=jdbc:postgresql://localhost:5432/daily_activity
spring.datasource.username=postgres
spring.datasource.password=FirstBD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true